services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/htb/
    command: uv run fastapi run --reload --workers 4 --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:17
    volumes:
      - db:/var/lib/postgresql/data/
      # - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  db:
